"""
BOOTS BRAND — the asset pipeline, in one file.

The plugin keeps its NAME and drops every piece of its old art: the rail icon
was a generated portrait of a frightened man in a helmet, and the loading
screen was pure type. Both are now Pascaline, the editor's official mascot —
the same character the whole product uses, wearing the hard hat with the Pascal
logotype, and (the reason the name still fits) tan work boots.

Nothing here is generated by a model. Every pixel of Pascaline comes from the
official render pack, so the plugin can never drift off-model; this script only
frames her, lights her, and animates the frame around her.

  OUTPUTS (into ../../src/assets/)
    boots-icon.webp     512×512 static  — the badge: rail entry + panel header.
                        The FILENAME IS LOAD-BEARING: docs/qa/qa-boots-roster.mjs
                        finds the rail entry by img[src*="boots-icon"], because
                        the host renders that entry as an icon with no text and
                        no aria-label. Rename it and the QA script goes blind.
    boots-loader.webp   700×300 ANIMATED — the hero above the loading bar, in
                        both loading surfaces (hud.ts's in-game card and
                        drop-gate.tsx's share-link veil).

  WHY ANIMATED WEBP AND NOT GIF. The ask was "maybe animated gif during loading
  above the bar". WebP delivers the same thing strictly better here: a quarter
  of the bytes, 24-bit colour instead of a 256-entry palette (this art is a
  soft-shaded 3D render — a GIF palette bands it visibly), and — the practical
  part — src/assets.d.ts already declares `*.webp`, so the asset rides the
  existing static-import pipeline with no new module declaration and no change
  to the `.src` idiom in art.ts. Every browser that can run this plugin (it
  renders through WebGPU) has decoded animated WebP for years.

  THE MOTION IS ALL LOOP-EXACT. Frame N is frame 0: the sunburst turns exactly
  two ray-periods, the hazard rail scrolls exactly one stripe period, the bob
  runs two sine cycles, the spotlight pulse one. Nothing has to be cross-faded
  and there is no visible seam at the wrap.

  RUNNING IT
    git clone --depth=1 git@github.com:pascalorg/pascaline.git /tmp/pascaline
    python3 docs/brand/build-brand-assets.py            # writes src/assets/
    PASCALINE=/path/to/pascaline OUT=/tmp/x python3 docs/brand/build-brand-assets.py

  Needs Pillow + numpy. This is a one-shot art step, not part of the build:
  the outputs are committed, and CI never runs this.
"""

import math
import os
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
PASCALINE = os.environ.get('PASCALINE', '/tmp/pascaline')
OUT = os.environ.get('OUT', os.path.join(HERE, '..', '..', 'src', 'assets'))

#: The plugin's existing accent, kept on purpose — the JUMP IN button, the
#: depot hazard stripe and the loading card's rule are already this yellow, so
#: the new art reads as the same product rather than a bolt-on.
YELLOW = (232, 194, 41)
#: Plate base + the steel the spotlight lifts it to.
PLATE = (14, 17, 20)
PLATE_WEAVE = (20, 24, 28)
STEEL = (84, 99, 115)
SUNBURST = (52, 62, 74)

#: The three poses that share a head position to the pixel. Registration is why
#: the cycle reads as one character gesturing and not as three cross-fades:
#: `celebrate` and `point-left` are framed differently and would jump, so they
#: are deliberately not in the set.
POSES = ('thumbs-up', 'wave', 'hands-palm')

#: 24 frames at 80 ms = a 1.92 s loop, and divisible by len(POSES) so every
#: pose gets the same 8 frames.
W, H, FRAMES, FRAME_MS = 700, 300, 24, 80
SUN_RAYS = 18


def load(name: str) -> Image.Image:
    path = os.path.join(PASCALINE, 'png', f'{name}.png')
    if not os.path.exists(path):
        sys.exit(f'missing {path} — clone pascalorg/pascaline, or set PASCALINE=')
    return Image.open(path).convert('RGBA')


def head_anchor(im: Image.Image) -> tuple[int, int]:
    """(centre x of the hard hat, top y of the figure).

    The hat is the only large bright, unsaturated, fully opaque region in the
    top third of a pose, which makes it a far steadier anchor than the alpha
    bbox: the bbox moves with whichever arm is outstretched, so centring on it
    would swing her sideways on every pose change.
    """
    a = np.array(im)
    rgb = a[:, :, :3].astype(int)
    alpha = a[:, :, 3]
    hi, lo = rgb.max(2), rgb.min(2)
    hat = (alpha > 200) & (lo > 170) & ((hi - lo) < 40)
    ys_all, _ = np.where(alpha > 8)
    top = int(ys_all.min())
    limit = top + int((ys_all.max() - top) * 0.35)
    ys, xs = np.where(hat)
    keep = ys < limit
    return int(xs[keep].mean()), top


def figure(name: str, bot: float) -> tuple[Image.Image, int]:
    """A bust: hat top down to `bot` of the figure's height, plus the hat's x
    inside the crop (so callers can register poses on it)."""
    im = load(name)
    hat_x, top = head_anchor(im)
    box = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
    return im.crop((box[0], top, box[2], top + int((box[3] - top) * bot))), hat_x - box[0]


def backdrop(w: int, h: int, phase: float) -> Image.Image:
    """The plate behind her: weave, a slowly turning sunburst, a spotlight, and
    a warm hazard halo. `phase` is 0..1 across one loop."""
    base = Image.new('RGB', (w, h), PLATE)
    draw = ImageDraw.Draw(base)
    for x in range(-h, w + h, 15):
        draw.line([(x, 0), (x + h, h)], fill=PLATE_WEAVE, width=2)
    cx, cy = w // 2, int(h * 0.46)

    # Sunburst — the hero-card motif. Drawn on an oversized square centred on
    # her head so the rays are true radials, then cropped to the plate.
    span = max(w, h) * 3
    sun = Image.new('L', (span, span), 0)
    sd = ImageDraw.Draw(sun)
    step = 360 / SUN_RAYS
    start = phase * step * 2  # exactly two ray-periods per loop
    for k in range(SUN_RAYS):
        a0 = start + k * step
        sd.pieslice([0, 0, span, span], a0, a0 + step / 2, fill=255)
    sun = sun.crop((span // 2 - cx, span // 2 - cy, span // 2 - cx + w, span // 2 - cy + h))
    sun = sun.filter(ImageFilter.GaussianBlur(3))
    base = Image.composite(Image.new('RGB', (w, h), SUNBURST), base, sun.point(lambda v: int(v * 0.30)))

    # Spotlight — she wears a black jacket over a black tee, so without this she
    # is a silhouette on a dark plate.
    pulse = 0.86 + 0.14 * math.sin(phase * 2 * math.pi)
    glow = Image.new('L', (w, h), 0)
    gd = ImageDraw.Draw(glow)
    rx, ry = int(w * 0.36), int(h * 0.66)
    for i in range(30):
        t = i / 29
        s = 1 - t * 0.9
        gd.ellipse([cx - rx * s, cy - ry * s, cx + rx * s, cy + ry * s], fill=int(255 * (1 - t) ** 1.4))
    glow = glow.filter(ImageFilter.GaussianBlur(w // 16))
    base = Image.composite(Image.new('RGB', (w, h), STEEL), base, glow.point(lambda v: int(v * pulse)))

    # Hazard halo, kept low: enough to warm the plate behind the white hat.
    halo = Image.new('L', (w, h), 0)
    hd = ImageDraw.Draw(halo)
    for i in range(24):
        t = i / 23
        s = 1 - t * 0.92
        hd.ellipse([cx - w * 0.15 * s, cy - h * 0.34 * s, cx + w * 0.15 * s, cy + h * 0.34 * s],
                   fill=int(255 * (1 - t) ** 1.5))
    halo = halo.filter(ImageFilter.GaussianBlur(w // 20))
    return Image.composite(Image.new('RGB', (w, h), YELLOW), base, halo.point(lambda v: int(v * 0.22 * pulse)))


def hazard_rail(im: Image.Image, phase: float, h_frac: float) -> Image.Image:
    """The depot hazard stripe along the bottom edge, scrolling one full stripe
    period per loop. In the loading card this REPLACES the card's own CSS
    stripe — two of them stacked was one too many."""
    w, h = im.size
    band_h = max(4, int(h * h_frac))
    band = Image.new('RGB', (w, band_h), (21, 23, 26))
    bd = ImageDraw.Draw(band)
    p = int(band_h * 2.0)
    off = int(phase * p * 2) % (p * 2)
    for x in range(-p * 2, w + p * 2, p * 2):
        bd.polygon([(x + off, band_h), (x + off + p, 0), (x + off + p * 2, 0), (x + off + p, band_h)], fill=YELLOW)
    out = im.copy()
    out.paste(band, (0, h - band_h))
    return out


def edge_fade(im: Image.Image, frac: float = 0.09) -> Image.Image:
    """Soft left/right plate edges — the hero sits inside two dark surfaces
    (#14171b card, #0c0e10 veil) and a hard edge would look pasted on. Only the
    flanks: a full vignette crushed her face in the first pass."""
    w, h = im.size
    mask = Image.new('L', (w, h), 255)
    d = ImageDraw.Draw(mask)
    p = int(w * frac)
    for i in range(p):
        v = int(255 * (i / p) ** 0.8)
        d.line([(i, 0), (i, h)], fill=v)
        d.line([(w - 1 - i, 0), (w - 1 - i, h)], fill=v)
    return Image.composite(im, Image.new('RGB', (w, h), (12, 14, 16)), mask)


def build_loader() -> Image.Image:
    """The animated hero. She bobs, pops a touch on each new pose, and the
    plate lives behind her."""
    figs = [figure(p, bot=0.72) for p in POSES]
    frames = []
    for i in range(FRAMES):
        phase = i / FRAMES
        seg, local = divmod(i / FRAMES * len(POSES), 1.0)
        fig, hat_x = figs[int(seg)]
        # The pop decays inside each pose's 8 frames — a gesture landing, not a
        # zoom. exp() so it is over before the eye calls it movement.
        fh = int(H * 1.22 * (1.0 + 0.03 * math.exp(-local * 10)))
        fw = int(fig.width * fh / fig.height)
        scaled = fig.resize((fw, fh), Image.LANCZOS)
        bob = int(round(3 * math.sin(phase * 4 * math.pi)))
        layer = Image.new('RGBA', (W, H), (0, 0, 0, 0))
        layer.alpha_composite(scaled, (W // 2 - int(hat_x * fh / fig.height), int(H * 0.045) + bob))
        plate = backdrop(W, H, phase)
        plate.paste(layer.convert('RGB'), (0, 0), layer.getchannel('A'))
        frames.append(edge_fade(hazard_rail(plate, phase, h_frac=0.05)))
    return frames


def build_badge(size: int = 512) -> Image.Image:
    """The square mark.

    Sized against the ONE number that matters: the host renders a plugin's rail
    entry at 20×20 (`h-5 w-5` in use-plugin-panels.tsx) and lists it at 32×32 in
    the Plugins panel. At 20 px the whole recognition budget is the white cap
    shape, two dark eyes and the yellow rail — so this is a TIGHT portrait (hat
    to smile). Wider crops were rendered at 20 px and compared: taking in the
    collar and jacket turns the bottom half into one dark smear.
    """
    fig, hat_x = figure('thumbs-up', bot=0.42)
    fh = int(size * 0.90)
    fw = int(fig.width * fh / fig.height)
    scaled = fig.resize((fw, fh), Image.LANCZOS)
    layer = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    layer.alpha_composite(scaled, (size // 2 - int(hat_x * fh / fig.height), int(size * 0.05)))
    plate = backdrop(size, size, 0.0)
    plate.paste(layer.convert('RGB'), (0, 0), layer.getchannel('A'))
    return hazard_rail(plate, 0.0, h_frac=0.08)


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    icon_path = os.path.join(OUT, 'boots-icon.webp')
    loader_path = os.path.join(OUT, 'boots-loader.webp')

    build_badge().save(icon_path, 'WEBP', quality=88, method=6)
    frames = build_loader()
    frames[0].save(loader_path, save_all=True, append_images=frames[1:],
                   duration=FRAME_MS, loop=0, quality=68, method=6)

    for path in (icon_path, loader_path):
        print(f'{os.path.relpath(path, os.path.join(HERE, "..", ".."))}  '
              f'{os.path.getsize(path) / 1024:.0f} KB')


if __name__ == '__main__':
    main()
