/**
 * EMBED THE AVATAR — assets/pascaline.glb → src/game/pascaline-glb.ts, and the
 * talking-mouth plate assets/pascaline-face-open.jpg → src/game/pascaline-face-open.ts.
 *
 *     node scripts/embed-avatar.mjs [assets/pascaline.glb] [assets/pascaline-face-open.jpg]
 *     SKIP_FACE_OPEN=1 …            body only
 *     FACE_OPEN_QUALITY=60 …        sips re-encode quality for the plate (macOS; default 60)
 *
 * The plugin is a `file:` dependency copied into the host's node_modules, and
 * the host bundles it with Next; a binary asset has no reliable URL from in
 * there, and the mascot repo is private so there is no CDN to point at. So the
 * body ships INSIDE the plugin as base64, in a module that pascaline-model.ts
 * imports dynamically — one extra chunk, downloaded the first time a session
 * mounts a Pascaline and never otherwise. Chunked into short lines so the
 * generated file diffs and reviews like source.
 *
 * THE OPEN MOUTH is the same 1024 px plate repainted mid-word (round 1 drew it,
 * assets/README.md). The GLB's closed plate went through Blender's glTF export
 * at JPEG quality 82 (~58 KB); the repaint on disk is a 178 KB q≈95 file, so
 * it is re-encoded here (sips, quality 60 → ~85 KB) to sit next to the closed
 * one in size and grain. Where sips is missing (not macOS) the file is embedded
 * as-is — bigger, never wrong. Its own module: a second lazy chunk, fetched
 * once, only when a body with a face is instantiated.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const src = resolve(here, process.argv[2] ?? '../assets/pascaline.glb')
const dst = resolve(here, '../src/game/pascaline-glb.ts')

const bytes = readFileSync(src)
if (bytes.readUInt32LE(0) !== 0x46546c67) throw new Error(`${src} is not a GLB (magic mismatch)`)
const b64 = bytes.toString('base64')
const lines = []
for (let i = 0; i < b64.length; i += 100) lines.push(`  '${b64.slice(i, i + 100)}',`)

writeFileSync(
  dst,
  `// GENERATED by scripts/embed-avatar.mjs from ${src.split('/').slice(-2).join('/')} — do not edit.
// ${bytes.length} bytes, Draco GLB: Pascaline, skinned on the six-pivot rig (see pascaline-model.ts).

export const PASCALINE_GLB_BASE64: string = [
${lines.join('\n')}
].join('')
`,
)
console.log(`embedded ${bytes.length} bytes from ${src} → ${dst} (${lines.length} lines)`)

// ── The talking-mouth plate ──────────────────────────────────────────────────
if (process.env.SKIP_FACE_OPEN !== '1') {
  const faceSrc = resolve(here, process.argv[3] ?? '../assets/pascaline-face-open.jpg')
  const faceDst = resolve(here, '../src/game/pascaline-face-open.ts')
  const quality = Number(process.env.FACE_OPEN_QUALITY ?? 60)
  let faceBytes = readFileSync(faceSrc)
  if (faceBytes[0] !== 0xff || faceBytes[1] !== 0xd8) throw new Error(`${faceSrc} is not a JPEG (magic mismatch)`)
  let encoded = 'as-is'
  if (existsSync('/usr/bin/sips') && Number.isFinite(quality) && quality > 0 && quality < 100) {
    const tmp = join(tmpdir(), `boots-face-open-${process.pid}.jpg`)
    try {
      execFileSync('/usr/bin/sips', ['-s', 'format', 'jpeg', '-s', 'formatOptions', String(quality), faceSrc, '--out', tmp], {
        stdio: 'ignore',
      })
      const re = readFileSync(tmp)
      if (re[0] === 0xff && re[1] === 0xd8 && re.length < faceBytes.length) {
        faceBytes = re
        encoded = `sips q${quality}`
      }
    } finally {
      try {
        unlinkSync(tmp)
      } catch {}
    }
  }
  const faceB64 = faceBytes.toString('base64')
  const faceLines = []
  for (let i = 0; i < faceB64.length; i += 100) faceLines.push(`  '${faceB64.slice(i, i + 100)}',`)
  writeFileSync(
    faceDst,
    `// GENERATED by scripts/embed-avatar.mjs from ${faceSrc.split('/').slice(-2).join('/')} (${encoded}) — do not edit.
// ${faceBytes.length} bytes, JPEG 1024×1024: the face plate repainted with the mouth open — the
// talking frame: a hidden twin of the face plate wears it and remote-players.tsx shows it while the peer talks (pascaline-model.ts setMouth).

export const PASCALINE_FACE_OPEN_JPG_BASE64: string = [
${faceLines.join('\n')}
].join('')
`,
  )
  console.log(`embedded ${faceBytes.length} bytes (${encoded}) from ${faceSrc} → ${faceDst} (${faceLines.length} lines)`)
}
