/**
 * EMBED THE AVATAR — assets/pascaline.glb → src/game/pascaline-glb.ts.
 *
 *     node scripts/embed-avatar.mjs [assets/pascaline.glb]
 *
 * The plugin is a `file:` dependency copied into the host's node_modules, and
 * the host bundles it with Next; a binary asset has no reliable URL from in
 * there, and the mascot repo is private so there is no CDN to point at. So the
 * body ships INSIDE the plugin as base64, in a module that pascaline-model.ts
 * imports dynamically — one extra chunk, downloaded the first time a session
 * mounts a Pascaline and never otherwise. Chunked into short lines so the
 * generated file diffs and reviews like source.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const src = resolve(here, process.argv[2] ?? '../assets/pascaline.glb')
const dst = resolve(here, '../src/game/pascaline-glb.ts')

const bytes = readFileSync(src)
if (bytes.readUInt32LE(0) !== 0x46546c67) throw new Error(`${src} is not a GLB (magic mismatch)`)
const b64 = bytes.toString('base64')
const lines = []
for (let i = 0; i < b64.length; i += 100) lines.push(`  '${b64.slice(i, i + 100)}',`)

writeFileSync(
  dst,
  `// GENERATED by scripts/embed-avatar.mjs from ${src.split('/').slice(-2).join('/')} — do not edit.
// ${bytes.length} bytes, Draco GLB: Pascaline, skinned on the six-pivot rig (see pascaline-model.ts).

export const PASCALINE_GLB_BASE64: string = [
${lines.join('\n')}
].join('')
`,
)
console.log(`embedded ${bytes.length} bytes from ${src} → ${dst} (${lines.length} lines)`)
